//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace DailyVetJobTxt {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class map {
        
        private mapEntry[] entryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entry")]
        public mapEntry[] entry {
            get {
                return this.entryField;
            }
            set {
                this.entryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class mapEntry {
        
        private bool hasNextPageField;
        
        private bool hasNextPageFieldSpecified;
        
        private bool hasPreviousPageField;
        
        private bool hasPreviousPageFieldSpecified;
        
        private mapEntryJobSearchPosting[] jobPostingsField;
        
        private byte responseCodeField;
        
        private bool responseCodeFieldSpecified;
        
        private byte totalField;
        
        private bool totalFieldSpecified;
        
        private object addedMocField;
        
        private string[] citiesField;
        
        private byte datePostedField;
        
        private bool datePostedFieldSpecified;
        
        private string locationField;
        
        private byte maxField;
        
        private bool maxFieldSpecified;
        
        private object mocField;
        
        private object mocIdsField;
        
        private object moc_idField;
        
        private byte offsetField;
        
        private bool offsetFieldSpecified;
        
        private string orderField;
        
        private string qField;
        
        private object selectedCivilianEquivalentIdsField;
        
        private object selectedMocIdField;
        
        private string sortField;
        
        private string[] statesField;
        
        private string keyField;
        
        /// <remarks/>
        public bool hasNextPage {
            get {
                return this.hasNextPageField;
            }
            set {
                this.hasNextPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hasNextPageSpecified {
            get {
                return this.hasNextPageFieldSpecified;
            }
            set {
                this.hasNextPageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool hasPreviousPage {
            get {
                return this.hasPreviousPageField;
            }
            set {
                this.hasPreviousPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hasPreviousPageSpecified {
            get {
                return this.hasPreviousPageFieldSpecified;
            }
            set {
                this.hasPreviousPageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("jobSearchPosting", IsNullable=false)]
        public mapEntryJobSearchPosting[] jobPostings {
            get {
                return this.jobPostingsField;
            }
            set {
                this.jobPostingsField = value;
            }
        }
        
        /// <remarks/>
        public byte responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool responseCodeSpecified {
            get {
                return this.responseCodeFieldSpecified;
            }
            set {
                this.responseCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public byte total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public object addedMoc {
            get {
                return this.addedMocField;
            }
            set {
                this.addedMocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] cities {
            get {
                return this.citiesField;
            }
            set {
                this.citiesField = value;
            }
        }
        
        /// <remarks/>
        public byte datePosted {
            get {
                return this.datePostedField;
            }
            set {
                this.datePostedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datePostedSpecified {
            get {
                return this.datePostedFieldSpecified;
            }
            set {
                this.datePostedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public byte max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxSpecified {
            get {
                return this.maxFieldSpecified;
            }
            set {
                this.maxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public object moc {
            get {
                return this.mocField;
            }
            set {
                this.mocField = value;
            }
        }
        
        /// <remarks/>
        public object mocIds {
            get {
                return this.mocIdsField;
            }
            set {
                this.mocIdsField = value;
            }
        }
        
        /// <remarks/>
        public object moc_id {
            get {
                return this.moc_idField;
            }
            set {
                this.moc_idField = value;
            }
        }
        
        /// <remarks/>
        public byte offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public string q {
            get {
                return this.qField;
            }
            set {
                this.qField = value;
            }
        }
        
        /// <remarks/>
        public object selectedCivilianEquivalentIds {
            get {
                return this.selectedCivilianEquivalentIdsField;
            }
            set {
                this.selectedCivilianEquivalentIdsField = value;
            }
        }
        
        /// <remarks/>
        public object selectedMocId {
            get {
                return this.selectedMocIdField;
            }
            set {
                this.selectedMocIdField = value;
            }
        }
        
        /// <remarks/>
        public string sort {
            get {
                return this.sortField;
            }
            set {
                this.sortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] states {
            get {
                return this.statesField;
            }
            set {
                this.statesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class mapEntryJobSearchPosting {
        
        private string addressLocalityField;
        
        private string addressRegionField;
        
        private object baseSalaryField;
        
        private object benefitsField;
        
        private object clicksField;
        
        private string datePostedField;
        
        private string descriptionField;
        
        private object educationRequirementsField;
        
        private object employmentTypeField;
        
        private object experienceRequirementsField;
        
        private string hiringOrganizationField;
        
        private object incentivesField;
        
        private object industryField;
        
        private object occupationalCategoryField;
        
        private string postalCodeField;
        
        private object qualificationsField;
        
        private object responsibilitiesField;
        
        private object salaryCurrencyField;
        
        private object searchesField;
        
        private object skillsField;
        
        private string snippetField;
        
        private string titleField;
        
        private string urlField;
        
        private object veteranCommitmentField;
        
        private object workHoursField;
        
        /// <remarks/>
        public string addressLocality {
            get {
                return this.addressLocalityField;
            }
            set {
                this.addressLocalityField = value;
            }
        }
        
        /// <remarks/>
        public string addressRegion {
            get {
                return this.addressRegionField;
            }
            set {
                this.addressRegionField = value;
            }
        }
        
        /// <remarks/>
        public object baseSalary {
            get {
                return this.baseSalaryField;
            }
            set {
                this.baseSalaryField = value;
            }
        }
        
        /// <remarks/>
        public object benefits {
            get {
                return this.benefitsField;
            }
            set {
                this.benefitsField = value;
            }
        }
        
        /// <remarks/>
        public object clicks {
            get {
                return this.clicksField;
            }
            set {
                this.clicksField = value;
            }
        }
        
        /// <remarks/>
        public string datePosted {
            get {
                return this.datePostedField;
            }
            set {
                this.datePostedField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public object educationRequirements {
            get {
                return this.educationRequirementsField;
            }
            set {
                this.educationRequirementsField = value;
            }
        }
        
        /// <remarks/>
        public object employmentType {
            get {
                return this.employmentTypeField;
            }
            set {
                this.employmentTypeField = value;
            }
        }
        
        /// <remarks/>
        public object experienceRequirements {
            get {
                return this.experienceRequirementsField;
            }
            set {
                this.experienceRequirementsField = value;
            }
        }
        
        /// <remarks/>
        public string hiringOrganization {
            get {
                return this.hiringOrganizationField;
            }
            set {
                this.hiringOrganizationField = value;
            }
        }
        
        /// <remarks/>
        public object incentives {
            get {
                return this.incentivesField;
            }
            set {
                this.incentivesField = value;
            }
        }
        
        /// <remarks/>
        public object industry {
            get {
                return this.industryField;
            }
            set {
                this.industryField = value;
            }
        }
        
        /// <remarks/>
        public object occupationalCategory {
            get {
                return this.occupationalCategoryField;
            }
            set {
                this.occupationalCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public object qualifications {
            get {
                return this.qualificationsField;
            }
            set {
                this.qualificationsField = value;
            }
        }
        
        /// <remarks/>
        public object responsibilities {
            get {
                return this.responsibilitiesField;
            }
            set {
                this.responsibilitiesField = value;
            }
        }
        
        /// <remarks/>
        public object salaryCurrency {
            get {
                return this.salaryCurrencyField;
            }
            set {
                this.salaryCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public object searches {
            get {
                return this.searchesField;
            }
            set {
                this.searchesField = value;
            }
        }
        
        /// <remarks/>
        public object skills {
            get {
                return this.skillsField;
            }
            set {
                this.skillsField = value;
            }
        }
        
        /// <remarks/>
        public string snippet {
            get {
                return this.snippetField;
            }
            set {
                this.snippetField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public object veteranCommitment {
            get {
                return this.veteranCommitmentField;
            }
            set {
                this.veteranCommitmentField = value;
            }
        }
        
        /// <remarks/>
        public object workHours {
            get {
                return this.workHoursField;
            }
            set {
                this.workHoursField = value;
            }
        }
    }
}
