<?xml version="1.0" encoding="utf-8"?><Database Name="VetTxt" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=VetTxt;Persist Security Info=True;User ID=sa;Pooling=False" SettingsObjectName="LData.Properties.Settings" SettingsPropertyName="VetTxtConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SentListings" Member="SentListings">
    <Type Name="SentListing">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="VarChar(5000) NOT NULL" CanBeNull="false" />
      <Column Name="DatePosted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PhoneUsers" Member="PhoneUsers">
    <Type Name="PhoneUser">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateActivated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateLastAccessed" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PIN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ZipCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KeyWords" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>